name = "lacocaim/bitkaisen"
version = "0.1.0"
description = "BitLife-style Jujutsu Kaisen life simulator"
authors = ["lacocaim"]
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/upliftgames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
Fusion = { wally = "elttob/fusion", version = "0.2.0" }
sift = { wally = "csqrl/sift", version = "0.0.11" }
gt = { wally = "corecii/greentea", version = "0.4.11" }

delta-compress = { wally = "nezuo/delta-compress", version = "0.1.3" }
profilestore = { wally = "lm-loleris/profilestore", version = "^1.0.3" }
charm = { wally = "littensy/charm", version = "^0.11.0-rc.5" }
vide = { repo = "https://github.com/bravobravo909/vide", rev = "24e1a9bd24fef896a10620ac1851aa26f78809ed" }
ripple = { wally = "littensy/ripple", version = "0.10.2" }
